// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Inquiry"
          text="Start your journey to the summit of luxury. Contact our concierge team today."
          primaryButton={{
            text: "Contact Concierge",
            href: "#",
          }}
          secondaryButton={{
            text: "Check Availability",
            href: "#",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
