// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSplitMedia
          tag="Info"
          title="Frequently Asked"
          description="Everything you need for a seamless stay."
          items={[
            {
              question: "What is the best season to visit?",
              answer: "The Alps offer unique experiences year-round, from pristine winter skiing to lush summer hikes.",
            },
            {
              question: "Do you offer private transfers?",
              answer: "Yes, we provide luxury helicopter and chauffeured limousine services to our resort.",
            },
            {
              question: "Are children welcome?",
              answer: "We welcome families and provide specialized services to ensure everyone enjoys their stay.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/designer-sauna-heaters-geometric-forms-sunny-interior_169016-68905.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
