// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesBentoGrid
          tag="Elevate Your Stay"
          title="Curated Experiences"
          description="From private wellness retreats to high-altitude adventures, every detail is crafted for your utmost comfort."
          features={[
            {
              title: "Wellness Sanctuary",
              description: "Experience deep rejuvenation in our world-class spa facilities overlooking the peaks.",
              imageSrc: "http://img.b2bpic.net/free-photo/panoramic-lakeside-sauna-geometric-heaters-scandinavian-style_169016-68879.jpg",
            },
            {
              title: "Culinary Excellence",
              description: "Savor authentic Swiss flavors paired with international delicacies at our fine-dining restaurant.",
              imageSrc: "http://img.b2bpic.net/free-photo/crispy-fried-crepes-stuffed-with-minced-meat-herb-garnished-with-sauce_140725-5793.jpg",
            },
            {
              title: "Mountain Suites",
              description: "Wake up to stunning sunrise views in our meticulously designed luxury suites.",
              imageSrc: "http://img.b2bpic.net/free-photo/indoor-design-luxury-resort_23-2150497281.jpg",
            },
            {
              title: "Exclusive Access",
              description: "Enjoy private helicopter transfers and personalized guides to secret alpine spots.",
              imageSrc: "http://img.b2bpic.net/free-photo/amazing-shot-human-flying-hang-glider_181624-21757.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
