/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import AutoFillText from "@/components/ui/AutoFillText";
import Tag from "@/components/ui/Tag";
import { Star } from "lucide-react";

const primaryButton = {
  text: "Reserve Now",
  href: "#contact"
};
const secondaryButton = {
  text: "Explore Experiences",
  href: "#features"
};

type HeroBrandProps = {
  brand: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const HeroInline = () => {
  return (
    <section
      aria-label="Hero section"
      className="relative w-full h-svh overflow-hidden flex flex-col justify-end mb-20"
    >
      <HeroBackgroundSlot />
      <ImageOrVideo
        imageSrc={"http://img.b2bpic.net/free-photo/gondola-cable-car-mountains_1204-282.jpg"}
        className="absolute inset-0 w-full h-full object-cover rounded-none"
      />

      <div
        className="absolute z-10 w-full h-[50svh] md:h-[75svh] left-0 bottom-0 backdrop-blur-xl mask-[linear-gradient(to_bottom,transparent,black_60%)]"
        aria-hidden="true"
      />

      <div className="relative z-10 w-content-width mx-auto pb-5">
        <div className="flex flex-col">
          <div className="w-full flex flex-col md:flex-row md:justify-between items-start md:items-end gap-3 md:gap-5">
            <div className="w-full md:w-1/2 flex flex-col gap-4">
              <div className="w-fit flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white/80 text-black border border-white/30 backdrop-blur-md text-sm font-medium">
                <div className="flex items-center gap-0.5">
                  <Star className="w-4 h-4 fill-black text-black" />
                  <Star className="w-4 h-4 fill-black text-black" />
                  <Star className="w-4 h-4 fill-black text-black" />
                  <Star className="w-4 h-4 fill-black text-black" />
                  <Star className="w-4 h-4 fill-black text-black" />
                </div>
                <span>5 star reviews</span>
              </div>
              <TextAnimation
                text={"Redefining alpine elegance. Discover a sanctuary of unparalleled luxury nestled in the heart of the Swiss Alps, where breathtaking vistas meet world-class service."}
                variant="slide-up"
                gradientText={false}
                tag="p"
                className="text-lg md:text-2xl text-balance font-normal text-white leading-snug"
              />
            </div>

            <div className="w-full md:w-1/2 flex justify-start md:justify-end">
              <div className="flex flex-wrap gap-3">
                <Button text={primaryButton.text} href={primaryButton.href} variant="primary"/>
                <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary"animationDelay={0.1} />
              </div>
            </div>
          </div>

          <AutoFillText className="font-semibold text-white">{"ALPINE LUXE"}</AutoFillText>
        </div>
      </div>
    </section>
  );
};

export default function HeroSection() {
  return (
    <div data-webild-section="hero" id="hero">
      <HeroInline />
    </div>
  );
}
