// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsIconCards from '@/components/sections/metrics/MetricsIconCards';
import { Award, Mountain, Star } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsIconCards
          tag="Our Impact"
          title="The Alpine Standard"
          description="Statistics that define our excellence in hospitality."
          metrics={[
            {
              icon: Star,
              title: "Guest Rating",
              value: "4.9/5",
            },
            {
              icon: Award,
              title: "Luxury Awards",
              value: "24",
            },
            {
              icon: Mountain,
              title: "Altitudes Reached",
              value: "4000m+",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
