// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesRevealCardsBento
          tag="Adventures"
          title="Winter & Summer Highlights"
          description="Bespoke itineraries designed by our local mountain specialists."
          items={[
            {
              title: "Off-Piste Skiing",
              description: "Unlimited access to pristine, untouched powder.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-view-ski-slope-surrounded-by-trees-bosnia-herzegovina_181624-36432.jpg",
            },
            {
              title: "Alpine Trekking",
              description: "Guided paths through ancient forests and meadows.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/men-trekking-nature_23-2148106689.jpg",
            },
            {
              title: "Peak Climbing",
              description: "Breathtaking ascents with experienced mountain guides.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/person-climbing-mountains-around-watzmannhaus-sunny-day_181624-5842.jpg",
            },
            {
              title: "Winter Safaris",
              description: "Speed through snowy landscapes on exclusive tours.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/winter-scene-with-people-snowboarding_23-2151472510.jpg",
            },
            {
              title: "Mountain Yoga",
              description: "Morning sessions on the plateau at sunrise.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-practices-yoga-morning-terrace-fresh-air_1153-4922.jpg",
            },
            {
              title: "Sommelier Tastings",
              description: "Private tastings of the rarest Swiss wines.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/bottles-with-champagne-are-cooling-pail-with-ice-bottles-with-wine-are-near_8353-9526.jpg",
            },
            {
              title: "Observatory Nights",
              description: "Clear night-sky viewing at our private station.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/young-man-sitting-logs-near-campfire-mountains-sky-full-stars_651396-3451.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
