// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialQuoteCards from '@/components/sections/testimonial/TestimonialQuoteCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialQuoteCards
          tag="Testimonials"
          title="Voices of the Mountains"
          testimonials={[
            {
              name: "Anna S.",
              role: "Traveler",
              quote: "The most exclusive experience in the Alps. Everything was perfection.",
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-handsome-middle-aged-business-leader_1262-4822.jpg",
            },
            {
              name: "Marcus V.",
              role: "CEO",
              quote: "I have traveled everywhere, but this hospitality level is unmatched.",
              imageSrc: "http://img.b2bpic.net/free-photo/confident-beautiful-young-woman-portrait_23-2148148150.jpg",
            },
            {
              name: "Elena R.",
              role: "Architect",
              quote: "Beautifully designed space. A truly rejuvenating sanctuary.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-sexy-handsome-fashion-male-model-man-dressed-elegant-suit-black-studio-lights-background_158538-9660.jpg",
            },
            {
              name: "James B.",
              role: "Adventureist",
              quote: "Unparalleled access to the best trails and powder in the world.",
              imageSrc: "http://img.b2bpic.net/free-photo/pretty-smiling-woman-dressed-black-sweater-posing_114579-81852.jpg",
            },
            {
              name: "Sophie M.",
              role: "Curator",
              quote: "The attention to detail and personal service was impeccable.",
              imageSrc: "http://img.b2bpic.net/free-photo/pretty-smiling-woman-dressed-black-sweater-posing_114579-81856.jpg",
            },
          ]}
          description="What our distinguished guests have to say about their experience."
        />
        </SectionErrorBoundary>
      </div>
  );
}
